[global]
width = 512
height = 512
output_dir = "./dist"

[mandelbrot]
x_min = -2.2
x_max = 0.8
y_min = -1.5
y_max = 1.5
threshold = 4
max_iterations = 20
color = 100
background_color = "black"
output_file = "mandelbrot.png"

[julia]
x_min = -1.5
x_max = 1.5
y_min = -1.5
y_max = 1.5
cx = -0.4
cy = 0.6
threshold = 4
max_iterations = 70
color = 220
background_color = "black"
output_file = "julia.png"

[tricorn]
x_min = -2.3
x_max = 1.7
y_min = -2.0
y_max = 2.0
max_iterations = 50
threshold = 4
color = 160
background_color = 'black'
output_file = 'tricorn.png'

[burning_ship]
x_min = -1.8
x_max = -1.7
y_min = -0.1
y_max = 0.02
max_iterations = 20
threshold = 10
color = 80
background_color = "black"
output_file = "burning_ship.png"

[barnsley_fern]
size_x = 10.0
size_y = 95.0
start_x = 48.0
start_y = 0.0
zoom = 90.0
max_iterations = 300000
color = "green"
background_color = "white"
output_file = "barnsley_fern.png"

[pythagoras_tree]
color_from = 0
color_upto = 320
size = 15
degree = 60
max_iterations = 10
left = 35
bottom = 20
output_file = "pythagoras_tree.png"
