[global]
width = 512
height = 512
output_dir = "./dist"

[mandelbrot]
x_min = -2.2
x_max = 0.8
y_min = -1.5
y_max = 1.5
threshold = 4
max_iterations = 20
color = 100
background_color = "black"
output_file = "mandelbrot.png"

[julia]
x_min = -1.5
x_max = 1.5
y_min = -1.5
y_max = 1.5
cx = -0.4
cy = 0.6
threshold = 4
max_iterations = 70
color = 220
background_color = "black"
output_file = "julia.png"

[tricorn]
x_min = -2.3
x_max = 1.7
y_min = -2.0
y_max = 2.0
max_iterations = 50
threshold = 4
color = 160
background_color = 'black'
output_file = 'tricorn.png'
